ARG GO_VERSION=1.26.2

FROM golang:${GO_VERSION}-alpine AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY ops/local/stubs/ ops/local/stubs/

ENV CGO_ENABLED=0 GOOS=linux
RUN go build -trimpath -ldflags="-s -w" -o /out/sophia-stubs ./ops/local/stubs

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /out/sophia-stubs /usr/local/bin/sophia-stubs
USER nonroot:nonroot
EXPOSE 9001 9002 9003
ENTRYPOINT ["/usr/local/bin/sophia-stubs"]
