package apply

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/RVRTelecomunicaciones/sophia-orchestrator/internal/ports/outbound"
)

// BuildPlan describes the build command resolved for a group worktree.
type BuildPlan struct {
	// Manifest is the file that triggered this plan (e.g. "go.mod").
	Manifest string
	// Command is the executable to run (e.g. "go").
	Command string
	// Args are the arguments passed to Command (e.g. ["build", "./..."]).
	Args []string
	// TimeoutMS is the per-attempt build timeout in milliseconds.
	TimeoutMS int
}

// BuildRule is a single manifest resolver. Resolve probes cwd and returns
// a BuildPlan when the rule fires, or (nil, false, nil) when no matching
// manifest is found. A non-nil error signals a probe failure that the
// caller should surface.
type BuildRule interface {
	Resolve(ctx context.Context, runtime outbound.RuntimeClient, cwd string) (*BuildPlan, bool, error)
}

// defaultBuildTimeoutMS is used when a rule does not set a custom timeout.
const defaultBuildTimeoutMS = 600_000 // 10 minutes

// ----- go rule --------------------------------------------------------

type goModRule struct{}

func (goModRule) Resolve(ctx context.Context, runtime outbound.RuntimeClient, cwd string) (*BuildPlan, bool, error) {
	exists, err := fileExistsInWorktree(ctx, runtime, cwd, "go.mod")
	if err != nil {
		return nil, false, fmt.Errorf("go.mod probe: %w", err)
	}
	if !exists {
		return nil, false, nil
	}
	return &BuildPlan{
		Manifest:  "go.mod",
		Command:   "go",
		Args:      []string{"build", "./..."},
		TimeoutMS: defaultBuildTimeoutMS,
	}, true, nil
}

// ----- package.json rule ----------------------------------------------

type packageJSONRule struct{}

func (packageJSONRule) Resolve(ctx context.Context, runtime outbound.RuntimeClient, cwd string) (*BuildPlan, bool, error) {
	exists, err := fileExistsInWorktree(ctx, runtime, cwd, "package.json")
	if err != nil {
		return nil, false, fmt.Errorf("package.json probe: %w", err)
	}
	if !exists {
		return nil, false, nil
	}

	// Read the file to check for scripts.build.
	raw, err := readFileInWorktree(ctx, runtime, cwd, "package.json")
	if err != nil {
		return nil, false, fmt.Errorf("package.json read: %w", err)
	}

	var pkg struct {
		Scripts map[string]string `json:"scripts"`
	}
	if err := json.Unmarshal(raw, &pkg); err != nil {
		// Malformed package.json — treat as no build script.
		return nil, false, nil
	}
	if _, hasBuild := pkg.Scripts["build"]; !hasBuild {
		return nil, false, nil
	}

	return &BuildPlan{
		Manifest:  "package.json",
		Command:   "npm",
		Args:      []string{"run", "build"},
		TimeoutMS: defaultBuildTimeoutMS,
	}, true, nil
}

// ----- pubspec.yaml rule ----------------------------------------------

type pubspecRule struct{}

func (pubspecRule) Resolve(ctx context.Context, runtime outbound.RuntimeClient, cwd string) (*BuildPlan, bool, error) {
	exists, err := fileExistsInWorktree(ctx, runtime, cwd, "pubspec.yaml")
	if err != nil {
		return nil, false, fmt.Errorf("pubspec.yaml probe: %w", err)
	}
	if !exists {
		return nil, false, nil
	}

	// Detect Flutter via .flutter-plugins or flutter dependency in pubspec.
	isFlutter := isFlutterProject(ctx, runtime, cwd)
	if isFlutter {
		return &BuildPlan{
			Manifest:  "pubspec.yaml",
			Command:   "flutter",
			Args:      []string{"build", "apk", "--release"},
			TimeoutMS: defaultBuildTimeoutMS,
		}, true, nil
	}

	// Dart fallback — only when a lib/main.dart entrypoint exists.
	hasEntrypoint, err := fileExistsInWorktree(ctx, runtime, cwd, filepath.Join("lib", "main.dart"))
	if err != nil {
		return nil, false, fmt.Errorf("dart entrypoint probe: %w", err)
	}
	if !hasEntrypoint {
		// No resolvable entrypoint — treat as no runnable build plan.
		return nil, false, nil
	}

	return &BuildPlan{
		Manifest:  "pubspec.yaml",
		Command:   "dart",
		Args:      []string{"compile", "exe", "lib/main.dart"},
		TimeoutMS: defaultBuildTimeoutMS,
	}, true, nil
}

// isFlutterProject checks for Flutter-specific markers inside cwd.
// We check for .flutter-plugins (generated by `flutter pub get`) and
// flutter_sdk or sdk: flutter inside pubspec.yaml. Best-effort: errors
// from probes are treated as "not Flutter" to preserve skip behaviour.
func isFlutterProject(ctx context.Context, runtime outbound.RuntimeClient, cwd string) bool {
	if ok, err := fileExistsInWorktree(ctx, runtime, cwd, ".flutter-plugins"); err == nil && ok {
		return true
	}

	raw, err := readFileInWorktree(ctx, runtime, cwd, "pubspec.yaml")
	if err != nil {
		return false
	}
	content := string(raw)
	return strings.Contains(content, "sdk: flutter") || strings.Contains(content, "flutter_sdk")
}

// DetectBuildPlan runs the ordered resolver chain and returns the first
// matching BuildPlan. Returns (nil, false, nil) when no manifest is
// recognised (skip path). The rule order is Go → Node → Dart/Flutter,
// which matches the most common monorepo layouts.
func DetectBuildPlan(ctx context.Context, runtime outbound.RuntimeClient, cwd string) (*BuildPlan, bool, error) {
	rules := []BuildRule{
		goModRule{},
		packageJSONRule{},
		pubspecRule{},
	}
	for _, rule := range rules {
		plan, matched, err := rule.Resolve(ctx, runtime, cwd)
		if err != nil {
			return nil, false, err
		}
		if matched {
			return plan, true, nil
		}
	}
	return nil, false, nil
}

// ----- low-level runtime probes ---------------------------------------

// fileExistsInWorktree uses shell.exec@v1 to test whether path exists
// inside cwd. We use `test -f` which exits 0 when the file is a regular
// file. Returns (false, nil) on non-zero exit (file absent), and
// (false, err) on runtime/transport errors.
func fileExistsInWorktree(ctx context.Context, runtime outbound.RuntimeClient, cwd, path string) (bool, error) {
	payload, err := json.Marshal(map[string]any{
		"command":     "test",
		"args":        []string{"-f", filepath.Join(cwd, path)},
		"working_dir": cwd,
	})
	if err != nil {
		return false, fmt.Errorf("marshal test payload: %w", err)
	}
	receipt, err := runtime.Execute(ctx, outbound.ExecutionRequest{
		Capability: "shell.exec@v1",
		Payload:    payload,
		TimeoutMS:  10_000,
	})
	if err != nil {
		return false, fmt.Errorf("shell.exec test: %w", err)
	}
	return receipt.ExitCode == 0, nil
}

// readFileInWorktree reads a file from the worktree via shell.exec cat.
func readFileInWorktree(ctx context.Context, runtime outbound.RuntimeClient, cwd, relPath string) ([]byte, error) {
	payload, err := json.Marshal(map[string]any{
		"command":     "cat",
		"args":        []string{filepath.Join(cwd, relPath)},
		"working_dir": cwd,
	})
	if err != nil {
		return nil, fmt.Errorf("marshal cat payload: %w", err)
	}
	receipt, err := runtime.Execute(ctx, outbound.ExecutionRequest{
		Capability: "shell.exec@v1",
		Payload:    payload,
		TimeoutMS:  10_000,
	})
	if err != nil {
		return nil, fmt.Errorf("shell.exec cat: %w", err)
	}
	if receipt.ExitCode != 0 {
		return nil, fmt.Errorf("cat %s exited %d", relPath, receipt.ExitCode)
	}
	return receipt.Stdout, nil
}
